logging:
  level:
    scott.barleydb: 
      server.jdbc:
        query:
          QueryExecuter: DEBUG
        persist:
          BatchExecuter: DEBUG
      api.persist:
         LoggingAuditor: DEBUG
